# needed to securely identify the workflow
name: autofix.ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
env:
  DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 📦 Install browsers
        run: pnpm playwright install

      - name: 🔠 Fix lint errors
        run: pnpm lint --fix

      - name: 🧪 Update unit test snapshots
        run: pnpm test:unit -u

      - name: 🏃 Update component test snapshots
        run: pnpm test:nuxt -u

      - name: 🖥️ Update browser test snapshots
        run: pnpm test:browser --update-snapshots

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
